// Send Message
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

// Continue Agent
export const CONTINUE_AGENT_REQUEST = "CONTINUE_AGENT_REQUEST";
export const CONTINUE_AGENT_SUCCESS = "CONTINUE_AGENT_SUCCESS";
export const CONTINUE_AGENT_FAILURE = "CONTINUE_AGENT_FAILURE";

// Messages Management
export const ADD_MESSAGE = "ADD_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const LOAD_MESSAGES_REQUEST = "LOAD_MESSAGES_REQUEST";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_FAILURE = "LOAD_MESSAGES_FAILURE";

// User Input
export const SET_USER_INPUT_FIELDS = "SET_USER_INPUT_FIELDS";
export const CLEAR_USER_INPUT_FIELDS = "CLEAR_USER_INPUT_FIELDS";
export const SET_WAITING_FOR_INPUT = "SET_WAITING_FOR_INPUT";

// WebSocket
export const WEBSOCKET_CONNECTED = "WEBSOCKET_CONNECTED";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED";
export const WEBSOCKET_ERROR = "WEBSOCKET_ERROR";

export const SET_AI_PROCESSING = 'SET_AI_PROCESSING';

