// Create Session
export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST"
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS"
export const CREATE_SESSION_FAILURE = "CREATE_SESSION_FAILURE"

// Set Session
export const SET_SESSION_ID = "SET_SESSION_ID"
export const CLEAR_SESSION = "CLEAR_SESSION"

// Session History
export const LOAD_SESSION_HISTORY_REQUEST = "LOAD_SESSION_HISTORY_REQUEST"
export const LOAD_SESSION_HISTORY_SUCCESS = "LOAD_SESSION_HISTORY_SUCCESS"
export const LOAD_SESSION_HISTORY_FAILURE = "LOAD_SESSION_HISTORY_FAILURE"

// Session Data
export const SET_SESSION_DATA = "SET_SESSION_DATA"
export const UPDATE_SESSION_DATA = "UPDATE_SESSION_DATA"
