// Register Actions
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

// Login Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// Logout Action
export const LOGOUT = "LOGOUT"

// Get User Profile
export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

// Verify Token
export const VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST"
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS"
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE"
